### ISSUE TITLE
test: run virtual against screen reader acceptance tests

### ISSUE THREAD

**Issue by jlp-craigmorten** [guidepup/virtual-screen-reader#21]
To build confidence that virtual is "spec compliant" it should be validated against a trusted set of acceptance tests.

Consider from:

1. https://a11ysupport.io/
2. https://aria-at.netlify.app/

**Comment by cmorten** [comment]
TBH maybe getting WPT as a submodule as running against actual browser a11y tests would be reasonable here.

There’s some copy paste WPT in the codebase, but not scalable to maintain and port that way.

See https://github.com/eps1lon/dom-accessibility-api/tree/main/tests for an example of how this could work
