### ISSUE TITLE
feat: Can navigate to next/prev heading

### ISSUE THREAD

**Issue by jcarstairs-scottlogic** [guidepup/virtual-screen-reader#50]
# Issue

Screen readers can typically navigate between headings. [Lots of screen readers use headings](https://webaim.org/projects/screenreadersurvey9/#heading) to navigate webpages, so it's an important feature to have.

## Details

I'm working on a solution which will add fourteen new commands:

* `moveToNextHeading`
* `moveToNextHeadingLevel1`
* `moveToNextHeadingLevel2`
* `moveToNextHeadingLevel3`
* `moveToNextHeadingLevel4`
* `moveToNextHeadingLevel5`
* `moveToNextHeadingLevel6`
* `moveToPreviousHeading`
* `moveToPreviousHeadingLevel1`
* `moveToPreviousHeadingLevel2`
* `moveToPreviousHeadingLevel3`
* `moveToPreviousHeadingLevel4`
* `moveToPreviousHeadingLevel5`
* `moveToPreviousHeadingLevel6`

**Comment by jlp-craigmorten** [comment]
Seems reasonable.

Curious that other roles mention that assistive technologies should enable users to navigate to them quickly but not for headings, which is probably one of the most common navigation methods.

https://www.w3.org/TR/wai-aria-1.2/#heading
