### ISSUE TITLE
feat: Playwright integration

### ISSUE THREAD

**Issue by cmorten** [guidepup/virtual-screen-reader#60]
# Issue

## Details

Integrating with Playwright is not currently the easiest as DOM access is somewhat abstracted away from.

It should be made easy to add VSR to the page and control and assert from a Playwright test.

TBC whether this needs to be a separate module.

**Comment by jlp-craigmorten** [comment]
For now we have ESM support allowing for usage via evaluations and adding script tags.

See https://github.com/guidepup/virtual-screen-reader/tree/main/examples/playwright
