### ISSUE TITLE
feat: implement `.moveToNextLink` && `.moveToPreviousLink` commands

### ISSUE THREAD

**Issue by philsherry** [guidepup/virtual-screen-reader#62]
Screen reader users navigate by a mix of headings and links. 

Adding these commands will make testing far more realistic. 

The commands for these menus are as follows: 
- <kbd>VO key</kbd> + <kbd>U</kbd> then arrow keys to the Links menu
- <kbd>JAWS key</kbd> + <kbd>F7</kbd>
- <kbd>NVDA key</kbd> + <kbd>F7</kbd>

**Comment by cmorten** [comment]
REF: https://webaim.org/projects/screenreadersurvey10/#finding

Looks to be ~4.8% of AT users navigate via links. Feels like a reasonable addition to me!
